name: texture_atlas_transformer
version: 1.0.1
description: A Pub transformer to build Texture Atlas JSON files.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/texture_atlas_transformer
environment:
  sdk: ">=1.19.0"
dependencies:
  barback: ^0.15.0
  glob: ^1.0.0
  image: ^1.0.0